name: 05-2. Hello World Composite

on:
  [workflow_dispatch]

permissions:
  contents: read

jobs:
  hello_world_job1:
    runs-on: ubuntu-latest
    name: A job1 to say hello
    steps:
      - id: hello-world
        # pinned to main branch
        uses: githubabcs/hello-world-composite-action@d03802b01530a2b620c5690210a1e637e9db5cbb
        with:
          who-to-greet: 'Hello from GH ABCs'
      - run: echo random-number ${{ steps.hello-world.outputs.random-number }}
        shell: bash