  name: Test Private Network Runner

  on:
    push:
      branches:
        - feature/story-3.1-add-computed-runners

  jobs:
    build:
      runs-on:
        group: jhhain-vnet-runners
        labels: [jhhain-vnet-runner]
      steps:
        - uses: actions/checkout@v4
        - name: Access private resource
          run: |
            echo "Connected to private network!"
